DATABASE = './dancecards_ehb2024.db'
IMPORT_CSV = 'participants_12_05_2024_dancecards.csv'
UPLOAD_FOLDER = './static/pix' # Simplicity
DEBUG = True
RALLY = 'EHB'
RALLYYEAR = '2024'
RALLYWYEAR = f'''{RALLY} {RALLYYEAR}'''
RALLYSITE = ''
APP_ADMIN = 'Martin'
TITLE = f'{RALLYWYEAR} Quartet Tramp Dance Card'
RALLYSCHEDULE= '/static/schedule.html'
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg'}
