DATABASE = './dancecards_hc2025.db'
IMPORT_CSV = 'dancecards_hc2025.csv'
UPLOAD_FOLDER = './static/pix' # Simplicity
DEBUG = True
RALLY = 'HC'
RALLYYEAR = '2025'
RALLYWYEAR = f'''{RALLY} {RALLYYEAR}'''
RALLYSITE = ''
APP_ADMIN = 'Martin'
TITLE = f'{RALLYWYEAR} Little Brigade Dance Card'
RALLYSCHEDULE= 'https://binghc2025.sched.com'
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg'}
